<?php

return [
    'typeBasic'=> ["title" => "基本段落樣式，由上至下排列，依序為主標題 > 影像+描述 > 副標題 > 內文＋按鈕。","key" => 'typeBasic'],
    'typeSL'=> ["title" => "由上至下排列，依序為主標題 > 影像+描述 > 副標題置左 > 內文＋按鈕置右。","key" => 'typeSL'],
    'typeSR'=> ["title" => "由上至下排列，依序為主標題 > 影像+描述 > 副標題置右 > 內文＋按鈕置左。","key" => 'typeSR'],
    'typeU'=> ["title" => "由上至下排列，依序為主標題 > 副標題 > 內文＋按鈕 > 影像+描述。","key" => 'typeU'],
    'typeUL'=> ["title" => "由上至下排列，依序為主標題置左 > 副標題 + 內文＋按鈕置右 > 影像+描述。","key" => 'typeUL'],
    'typeUR'=> ["title" => "由上至下排列，依序為主標題置右 > 副標題 + 內文＋按鈕置左 > 影像+描述。","key" => 'typeUR'],
    'typeU RWD'=> ["title" => "(手機圖上文下) 由上至下排列，依序為主標題 > 副標題 > 內文＋按鈕 > 影像+描述。","key" => 'typeU RWD'],
    'typeUL RWD'=> ["title" => "(手機圖上文下) 由上至下排列，依序為主標題置左 > 副標題 + 內文＋按鈕置右 > 影像+描述。","key" => 'typeUL RWD'],
    'typeUR RWD'=> ["title" => "(手機圖上文下) 由上至下排列，依序為主標題置右 > 副標題 + 內文＋按鈕置左 > 影像+描述。","key" => 'typeUR RWD'],
    'typeD'=> ["title" => "由上至下排列，依序為影像+描述 > 主標題 > 副標題 > 內文＋按鈕。","key" => 'typeD'],
    'typeDL'=> ["title" => "由上至下排列，依序為影像+描述 > 主標題置左 > 副標題 + 內文＋按鈕置右。","key" => 'typeDL'],
    'typeDR'=> ["title" => "由上至下排列，依序為影像+描述 > 主標題置右 > 副標題 + 內文＋按鈕置左。","key" => 'typeDR'],
    'typeL'=> ["title" => "依序為主標題 + 副標題 + 內文＋按鈕置左 > 影像+描述置右。","key" => 'typeL'],
    'typeR'=> ["title" => "依序為影像+描述置左 > 主標題 + 副標題 + 內文＋按鈕置右。","key" => 'typeR'],
    'typeLR'=> ["title" => "依序為主標題 + 副標題 + 內文＋按鈕置左圍繞影像+描述置右。","key" => 'typeLR'],
    'typeRR'=> ["title" => "依序為主標題 + 副標題 + 內文＋按鈕置右圍繞影像+描述置左。","key" => 'typeRR'],
    'typeF'=> ["title" => "滿版背景，段落垂直置中，由上至下依序為影像+描述 > 主標題 > 副標題 > 內文＋按鈕。","key" => 'typeF'],
    'typeFL'=> ["title" => "滿版背景，段落垂直置左，由上至下依序為影像+描述 > 主標題 > 副標題 > 內文＋按鈕。","key" => 'typeFL'],
    'typeFR'=> ["title" => "滿版背景，段落垂直置右，由上至下依序為影像+描述 > 主標題 > 副標題 > 內文＋按鈕。","key" => 'typeFR'],
    'typeFBox'=> ["title" => "滿版背景並使段落區塊中的內文區域產生色塊，段落垂直置中，由上至下依序為影像+描述 > 主標題 > 副標題 > 內文＋按鈕。","key" => 'typeFBox'],
    'typeFBoxL'=> ["title" => "滿版背景並使段落區塊中的內文區域產生色塊，段落垂直置左，由上至下依序為影像+描述 > 主標題 > 副標題 > 內文＋按鈕。","key" => 'typeFBoxL'],
    'typeFBoxR'=> ["title" => "滿版背景並使段落區塊中的內文區域產生色塊，段落垂直置右，由上至下依序為影像+描述 > 主標題 > 副標題 > 內文＋按鈕。","key" => 'typeFBoxR'],
    '_article -typeFull-BoxSlice'=> ["title" => "滿版背景，區塊預設為左右置中對齊，段落區塊左右置中垂直切割區塊，，由上至下依序為主標題 > 影像+描述 > 副標題 > 內文＋按鈕。","key" => '_article -typeFull-BoxSlice'],
    '_article -typeFull-BoxSlice-L'=> ["title" => "滿版背景，區塊預設為置左對齊，段落區塊置左垂直切割區塊，由上至下依序為主標題 > 影像+描述 > 副標題 > 內文＋按鈕。","key" => '_article -typeFull-BoxSlice-L'],
    '_article -typeFull-BoxSlice-R'=> ["title" => "滿版背景，區塊預設為置右對齊，段落區塊置右垂直切割區塊，由上至下依序為主標題 > 影像+描述 > 副標題 > 內文＋按鈕。","key" => '_article -typeFull-BoxSlice-R'],
    '_article -typeSwiper-L'=> ["title" => "設定段落為 Swiper 模式，段落內容由左至右依序為影像 > 主標題＋副標題＋內文＋按鈕","key" => '_article -typeSwiper-L'],
    '_article -typeSwiper-R'=> ["title" => "設定段落為 Swiper 模式，段落內容由左至右依序為主標題＋副標題＋內文＋按鈕 > 影像","key" => '_article -typeSwiper-R'],
    '_article -typeOverlap-LU'=> ["title" => "段落區塊由上至下編排，依序為影像*2-大圖置左小圖置右下 > 主標題 > 副標題 > 內文 > 按鈕","key" => '_article -typeOverlap-LU'],
    '_article -typeOverlap-LD'=> ["title" => "段落區塊由上至下編排，依序為主標題 > 副標題 > 內文 > 按鈕 > 影像*2-大圖置左小圖置右上","key" => '_article -typeOverlap-LD'],
    '_article -typeOverlap-RU'=> ["title" => "段落區塊由上至下編排，依序為影像*2-大圖置右小圖置左下 > 主標題 > 副標題 > 內文 > 按鈕","key" => '_article -typeOverlap-RU'],
    '_article -typeOverlap-RD'=> ["title" => "段落區塊由上至下編排，依序為影像*2-大圖置右小圖置左上 > 主標題 > 副標題 > 內文 > 按鈕","key" => '_article -typeOverlap-RD'],
];
