                                                [
                                                    'type' => 'datePicker',
                                                    'value' => '{$name}',
                                                    'title' => '{$title}',
                                                    'tip' => '{$tip}',
                                                    'default' => '',
                                                    'auto' => true,
                                                    'disabled' => '{$disabled}',
                                                    'class' => '',
                                                ],