                                                [
                                                    'type' => 'numberRange',
                                                    'value' => '{$name}_start',
                                                    'value2' => '{$name}_end',
                                                    'title' => '{$title}',
                                                    'tip' => '{$tip}',
                                                    'default' => '',
                                                    'auto' => true,
                                                    'disabled' => '{$disabled}',
                                                    'class' => '',
                                                ],