                                                [
                                                    'type' => 'select2',
                                                    'value' => '{$name}',
                                                    'title' => '{$title}',
													'options' => {$options},
                                                    'tip' => '{$tip}',
                                                    'default' => '',
                                                    'auto' => true,
                                                    'disabled' => '{$disabled}',
                                                ],