                                                [
                                                    'type' => 'textInputTargetAcc',
                                                    'value' => '{$name}',
                                                    'title' => '{$title}',
                                                    'tip' => '可輸入多行文字，內容支援HTML，不支援CSS、JQ、JS等語法，斷行請多利用Enter，輸入區域可拖曳右下角縮放。',
                                                    'default' => '',
                                                    'auto' => true,
                                                    'disabled' => '{$disabled}',
                                                    'class' => '',
                                                    'target' => ['name' => '{$name}_target'],
                                                    'accessible' => ['name' => '{$name}_acc'],
                                                ],