<?php

namespace App\Http\Controllers;

use Illuminate\Routing\Controller as BaseController;

use View;
use Redirect;
use Auth;
use Debugbar;
use Route;
use App;
use Config;
use Session;
use Carbon\Carbon;

class ExcelRelatedFunction extends BaseController
{

	public function __construct()
	{
		parent::__construct();
	}

	public static function AutoGet()
	{
		$array = [
			["model" => "News", "field" => "class_id", "from_model" => "Class_news", "from_field" => "w_title"],
			["model" => "News", "field" => "sitetag_id", "from_model" => "Sitetag", "from_field" => "w_title"],
			["model" => "Article", "field" => "class_id", "from_model" => "Class_article_sub", "from_field" => "w_title"],
			["model" => "Article", "field" => "sitetag_id", "from_model" => "Sitetag", "from_field" => "w_title"],
			["model" => "Seminar", "field" => "class_id", "from_model" => "Class_seminar", "from_field" => "w_title"],
			["model" => "Seminar", "field" => "filter", "from_model" => "Seminar_tag_item", "from_field" => "w_title"],
			["model" => "Seminar", "field" => "related", "from_model" => "Seminar", "from_field" => "w_title"],
			["model" => "Seminar", "field" => "sitetag_id", "from_model" => "Sitetag", "from_field" => "w_title"],
			["model" => "Seminar_lecturer", "field" => "lecturer_id", "from_model" => "Lecturer", "from_field" => "w_title"],
			["model" => "Seminar_signup", "field" => "seminar_id", "from_model" => "Seminar", "from_field" => "w_title"],
			["model" => "Seminar_signup", "field" => "w_sex", "from_model" => "CC_sex", "from_field" => "title"],
			["model" => "Seminar_signup", "field" => "w_job", "from_model" => "Job", "from_field" => "w_title"],
			["model" => "Seminar_signup", "field" => "food", "from_model" => "CC_food", "from_field" => "title"],
			["model" => "Seminar_signup", "field" => "w_state", "from_model" => "CC_signup_state", "from_field" => "title"],
			["model" => "Course", "field" => "class_id", "from_model" => "Class_course", "from_field" => "w_title"],
			["model" => "Course", "field" => "w_tag", "from_model" => "Course_tag_item", "from_field" => "w_title"],
			["model" => "Course", "field" => "filter", "from_model" => "Course_tag_item", "from_field" => "w_title"],
			["model" => "Course", "field" => "unit_id", "from_model" => "Society_unit", "from_field" => "w_title"],
			["model" => "Course", "field" => "license_id", "from_model" => "License", "from_field" => "w_title"],
			["model" => "Course", "field" => "sitetag_id", "from_model" => "Sitetag", "from_field" => "w_title"],
			["model" => "Coursetest", "field" => "class_id", "from_model" => "Class_coursetest", "from_field" => "w_title"],
			["model" => "Coursetest", "field" => "w_tag", "from_model" => "Coursetest_tag_item", "from_field" => "w_title"],
			["model" => "Coursetest", "field" => "filter", "from_model" => "Coursetest_tag_item", "from_field" => "w_title"],
			["model" => "Coursetest", "field" => "unit_id", "from_model" => "Society_unit", "from_field" => "w_title"],
			["model" => "Coursetest", "field" => "license_id", "from_model" => "License", "from_field" => "w_title"],
			["model" => "Coursetest", "field" => "sitetag_id", "from_model" => "Sitetag", "from_field" => "w_title"],
			["model" => "Course_from", "field" => "member_id", "from_model" => "Member", "from_field" => "w_title"],
			["model" => "Course_from", "field" => "cours_id", "from_model" => "Course", "from_field" => "w_title"],
			["model" => "Course_from", "field" => "unit_id", "from_model" => "Society_unit", "from_field" => "w_title"],
			["model" => "Course_from", "field" => "license_id", "from_model" => "License", "from_field" => "w_title"],
			["model" => "Course_from", "field" => "is_pass", "from_model" => "CC_yesno", "from_field" => "title"],
			["model" => "Course_from", "field" => "w_state", "from_model" => "CC_from_state", "from_field" => "title"],
			["model" => "Course_from", "field" => "credit_state", "from_model" => "CC_credit_state", "from_field" => "title"],
			["model" => "Coursetest_from", "field" => "member_id", "from_model" => "Member", "from_field" => "w_title"],
			["model" => "Coursetest_from", "field" => "cours_id", "from_model" => "Course", "from_field" => "w_title"],
			["model" => "Coursetest_from", "field" => "unit_id", "from_model" => "Society_unit", "from_field" => "w_title"],
			["model" => "Coursetest_from", "field" => "license_id", "from_model" => "License", "from_field" => "w_title"],
			["model" => "Coursetest_from", "field" => "is_pass", "from_model" => "CC_yesno", "from_field" => "title"],
			["model" => "Coursetest_from", "field" => "w_state", "from_model" => "CC_from_state", "from_field" => "title"],
			["model" => "Coursetest_from", "field" => "credit_state", "from_model" => "CC_credit_state", "from_field" => "title"],
			["model" => "Member_lovelist", "field" => "article_id", "from_model" => "Article", "from_field" => "w_title"],
			["model" => "News", "field" => "class_id", "from_model" => "Class_news", "from_field" => ""],
			["model" => "News", "field" => "sitetag_id", "from_model" => "Sitetag", "from_field" => ""],
			["model" => "Article", "field" => "class_id", "from_model" => "Class_article_sub", "from_field" => "w_title"],
			["model" => "Article", "field" => "sitetag_id", "from_model" => "Sitetag", "from_field" => ""],
			["model" => "Seminar", "field" => "class_id", "from_model" => "Class_seminar", "from_field" => ""],
			["model" => "Seminar", "field" => "filter", "from_model" => "Seminar_tag_item", "from_field" => "w_title"],
			["model" => "Seminar", "field" => "related", "from_model" => "Seminar", "from_field" => ""],
			["model" => "Seminar", "field" => "sitetag_id", "from_model" => "Sitetag", "from_field" => ""],
			["model" => "Seminar_lecturer", "field" => "lecturer_id", "from_model" => "Lecturer", "from_field" => ""],
			["model" => "Seminar_signup", "field" => "seminar_id", "from_model" => "Seminar", "from_field" => ""],
			["model" => "Seminar_signup", "field" => "w_sex", "from_model" => "CC_sex", "from_field" => "title"],
			["model" => "Seminar_signup", "field" => "w_job", "from_model" => "Job", "from_field" => ""],
			["model" => "Seminar_signup", "field" => "food", "from_model" => "CC_food", "from_field" => "title"],
			["model" => "Seminar_signup", "field" => "w_state", "from_model" => "CC_signup_state", "from_field" => "title"],
			["model" => "Course", "field" => "class_id", "from_model" => "Class_course", "from_field" => ""],
			["model" => "Course", "field" => "w_tag", "from_model" => "Course_tag_item", "from_field" => "w_title"],
			["model" => "Course", "field" => "filter", "from_model" => "Course_tag_item", "from_field" => "w_title"],
			["model" => "Course", "field" => "unit_id", "from_model" => "Society_unit", "from_field" => ""],
			["model" => "Course", "field" => "license_id", "from_model" => "License", "from_field" => ""],
			["model" => "Course", "field" => "sitetag_id", "from_model" => "Sitetag", "from_field" => ""],
			["model" => "Coursetest", "field" => "class_id", "from_model" => "Class_coursetest", "from_field" => ""],
			["model" => "Coursetest", "field" => "w_tag", "from_model" => "Coursetest_tag_item", "from_field" => "w_title"],
			["model" => "Coursetest", "field" => "filter", "from_model" => "Coursetest_tag_item", "from_field" => "w_title"],
			["model" => "Coursetest", "field" => "unit_id", "from_model" => "Society_unit", "from_field" => ""],
			["model" => "Coursetest", "field" => "license_id", "from_model" => "License", "from_field" => ""],
			["model" => "Coursetest", "field" => "sitetag_id", "from_model" => "Sitetag", "from_field" => ""],
			["model" => "Course_from", "field" => "member_id", "from_model" => "Member", "from_field" => "w_title"],
			["model" => "Course_from", "field" => "cours_id", "from_model" => "Course", "from_field" => ""],
			["model" => "Course_from", "field" => "unit_id", "from_model" => "Society_unit", "from_field" => ""],
			["model" => "Course_from", "field" => "license_id", "from_model" => "License", "from_field" => ""],
			["model" => "Course_from", "field" => "is_pass", "from_model" => "CC_yesno", "from_field" => "title"],
			["model" => "Course_from", "field" => "w_state", "from_model" => "CC_from_state", "from_field" => "title"],
			["model" => "Course_from", "field" => "credit_state", "from_model" => "CC_credit_state", "from_field" => "title"],
			["model" => "Coursetest_from", "field" => "member_id", "from_model" => "Member", "from_field" => "w_title"],
			["model" => "Coursetest_from", "field" => "cours_id", "from_model" => "Course", "from_field" => ""],
			["model" => "Coursetest_from", "field" => "unit_id", "from_model" => "Society_unit", "from_field" => ""],
			["model" => "Coursetest_from", "field" => "license_id", "from_model" => "License", "from_field" => ""],
			["model" => "Coursetest_from", "field" => "is_pass", "from_model" => "CC_yesno", "from_field" => "title"],
			["model" => "Coursetest_from", "field" => "w_state", "from_model" => "CC_from_state", "from_field" => "title"],
			["model" => "Coursetest_from", "field" => "credit_state", "from_model" => "CC_credit_state", "from_field" => "title"],
			["model" => "Member_lovelist", "field" => "article_id", "from_model" => "Article", "from_field" => ""],
			["model" => "Member_record", "field" => "member_id", "from_model" => "Member", "from_field" => "w_title"],
			["model" => "Member", "field" => "w_job", "from_model" => "Job", "from_field" => ""],
			["model" => "News", "field" => "class_id", "from_model" => "Class_news", "from_field" => ""],
			["model" => "News", "field" => "sitetag_id", "from_model" => "Sitetag", "from_field" => ""],
			["model" => "Article", "field" => "class_id", "from_model" => "Class_article_sub", "from_field" => "w_title"],
			["model" => "Article", "field" => "sitetag_id", "from_model" => "Sitetag", "from_field" => ""],
			["model" => "Seminar", "field" => "class_id", "from_model" => "Class_seminar", "from_field" => ""],
			["model" => "Seminar", "field" => "filter", "from_model" => "Seminar_tag_item", "from_field" => "w_title"],
			["model" => "Seminar", "field" => "related", "from_model" => "Seminar", "from_field" => ""],
			["model" => "Seminar", "field" => "sitetag_id", "from_model" => "Sitetag", "from_field" => ""],
			["model" => "Seminar_lecturer", "field" => "lecturer_id", "from_model" => "Lecturer", "from_field" => ""],
			["model" => "Seminar_signup", "field" => "seminar_id", "from_model" => "Seminar", "from_field" => ""],
			["model" => "Seminar_signup", "field" => "w_sex", "from_model" => "CC_sex", "from_field" => "title"],
			["model" => "Seminar_signup", "field" => "w_job", "from_model" => "Job", "from_field" => ""],
			["model" => "Seminar_signup", "field" => "food", "from_model" => "CC_food", "from_field" => "title"],
			["model" => "Seminar_signup", "field" => "w_state", "from_model" => "CC_signup_state", "from_field" => "title"],
			["model" => "Course", "field" => "class_id", "from_model" => "Class_course", "from_field" => ""],
			["model" => "Course", "field" => "w_tag", "from_model" => "Course_tag_item", "from_field" => "w_title"],
			["model" => "Course", "field" => "filter", "from_model" => "Course_tag_item", "from_field" => "w_title"],
			["model" => "Course", "field" => "unit_id", "from_model" => "Society_unit", "from_field" => ""],
			["model" => "Course", "field" => "license_id", "from_model" => "License", "from_field" => ""],
			["model" => "Course", "field" => "sitetag_id", "from_model" => "Sitetag", "from_field" => ""],
			["model" => "Coursetest", "field" => "class_id", "from_model" => "Class_coursetest", "from_field" => ""],
			["model" => "Coursetest", "field" => "w_tag", "from_model" => "Coursetest_tag_item", "from_field" => "w_title"],
			["model" => "Coursetest", "field" => "filter", "from_model" => "Coursetest_tag_item", "from_field" => "w_title"],
			["model" => "Coursetest", "field" => "unit_id", "from_model" => "Society_unit", "from_field" => ""],
			["model" => "Coursetest", "field" => "license_id", "from_model" => "License", "from_field" => ""],
			["model" => "Coursetest", "field" => "sitetag_id", "from_model" => "Sitetag", "from_field" => ""],
			["model" => "Course_from", "field" => "member_id", "from_model" => "Member", "from_field" => ""],
			["model" => "Course_from", "field" => "cours_id", "from_model" => "Course", "from_field" => ""],
			["model" => "Course_from", "field" => "unit_id", "from_model" => "Society_unit", "from_field" => ""],
			["model" => "Course_from", "field" => "license_id", "from_model" => "License", "from_field" => ""],
			["model" => "Course_from", "field" => "is_pass", "from_model" => "CC_yesno", "from_field" => "title"],
			["model" => "Course_from", "field" => "w_state", "from_model" => "CC_from_state", "from_field" => "title"],
			["model" => "Course_from", "field" => "credit_state", "from_model" => "CC_credit_state", "from_field" => "title"],
			["model" => "Coursetest_from", "field" => "member_id", "from_model" => "Member", "from_field" => ""],
			["model" => "Coursetest_from", "field" => "cours_id", "from_model" => "Course", "from_field" => ""],
			["model" => "Coursetest_from", "field" => "unit_id", "from_model" => "Society_unit", "from_field" => ""],
			["model" => "Coursetest_from", "field" => "license_id", "from_model" => "License", "from_field" => ""],
			["model" => "Coursetest_from", "field" => "is_pass", "from_model" => "CC_yesno", "from_field" => "title"],
			["model" => "Coursetest_from", "field" => "w_state", "from_model" => "CC_from_state", "from_field" => "title"],
			["model" => "Coursetest_from", "field" => "credit_state", "from_model" => "CC_credit_state", "from_field" => "title"],
			["model" => "Member", "field" => "w_job", "from_model" => "Job", "from_field" => ""],
			["model" => "Member_lovelist", "field" => "article_id", "from_model" => "Article", "from_field" => ""],
			["model" => "Member_record", "field" => "member_id", "from_model" => "Member", "from_field" => ""],
			["model" => "Gift_push", "field" => "product_id", "from_model" => "ProductItem", "from_field" => ""],
			["model" => "Faq", "field" => "class_id", "from_model" => "Class_faq", "from_field" => ""],
			["model" => "Store", "field" => "zip_id", "from_model" => "Store_zip", "from_field" => "w_title"],
			["model" => "Store", "field" => "zip_id", "from_model" => "Store_zip", "from_field" => ""],
			["model" => "Home_market_product", "field" => "product_id", "from_model" => "ProductItem", "from_field" => ""],
			["model" => "Home_market1_product", "field" => "product_id", "from_model" => "ProductItem", "from_field" => ""],
			["model" => "Home_gift_item", "field" => "product_id", "from_model" => "ProductItem", "from_field" => ""],
			["model" => "Home_about_item", "field" => "class_id", "from_model" => "Home_about_class", "from_field" => ""],
			["model" => "Home_market1", "field" => "w_algin", "from_model" => "CC_algin", "from_field" => "title"],
			["model" => "Home_setting", "field" => "market1_algin", "from_model" => "CC_algin", "from_field" => "title"],
			["model" => "Home_about_item", "field" => "parent_id", "from_model" => "Home_about_class", "from_field" => ""],
			["model" => "News", "field" => "class_id", "from_model" => "News_class", "from_field" => ""],
			["model" => "Setting_gift", "field" => "gift_object", "from_model" => "ProductCate", "from_field" => ""],
			["model" => "Setting_gift", "field" => "gift_situation", "from_model" => "ProductCate", "from_field" => ""],
			["model" => "Setting_gift", "field" => "gift_function", "from_model" => "ProductCate", "from_field" => ""],
			["model" => "Menu_product", "field" => "product_id", "from_model" => "ProductItem", "from_field" => ""],
			["model" => "Contact", "field" => "subject_id", "from_model" => "Contact_subject", "from_field" => "w_title"],
			["model" => "Contact", "field" => "w_sex", "from_model" => "CC_sex", "from_field" => "title"],
			["model" => "Event_product", "field" => "product_id", "from_model" => "ProductItem", "from_field" => ""],
["model"=>"Setting_gift","field"=>"gift_object","from_model"=>"ProductCate","from_field"=>""],
["model"=>"Setting_gift","field"=>"gift_situation","from_model"=>"ProductCate","from_field"=>""],
["model"=>"Setting_gift","field"=>"gift_function","from_model"=>"ProductCate","from_field"=>""],
["model"=>"Gift_push","field"=>"product_id","from_model"=>"ProductItem","from_field"=>""],
["model"=>"Faq","field"=>"class_id","from_model"=>"Class_faq","from_field"=>""],
["model"=>"Store","field"=>"zip_id","from_model"=>"Store_zip","from_field"=>"w_title"],
["model"=>"Home_setting","field"=>"market1_algin","from_model"=>"CC_algin","from_field"=>"title"],
["model"=>"Home_market_product","field"=>"product_id","from_model"=>"ProductItem","from_field"=>""],
["model"=>"Home_market1_product","field"=>"product_id","from_model"=>"ProductItem","from_field"=>""],
["model"=>"Home_gift_item","field"=>"product_id","from_model"=>"ProductItem","from_field"=>""],
["model"=>"Home_about_item","field"=>"parent_id","from_model"=>"Home_about_class","from_field"=>""],
["model"=>"News","field"=>"class_id","from_model"=>"News_class","from_field"=>""],
["model"=>"Contact","field"=>"subject_id","from_model"=>"Contact_subject","from_field"=>""],
["model"=>"Contact","field"=>"w_sex","from_model"=>"CC_sex","from_field"=>"title"],
["model"=>"Event_product","field"=>"product_id","from_model"=>"ProductItem","from_field"=>""],
["model"=>"Menu_product","field"=>"product_id","from_model"=>"ProductItem","from_field"=>""],
["model"=>"News","field"=>"w_description","from_model"=>"News_class","from_field"=>""],
["model"=>"Data_list","field"=>"a4","from_model"=>"Class_data","from_field"=>""],
["model"=>"Data_list","field"=>"a5","from_model"=>"Class_data","from_field"=>""],
["model"=>"Data_list1","field"=>"a4","from_model"=>"Class_data","from_field"=>""],
["model"=>"Data_list1","field"=>"a5","from_model"=>"Class_data","from_field"=>""],
["model"=>"Data_list2","field"=>"a4","from_model"=>"Class_data","from_field"=>""],
["model"=>"Data_list2","field"=>"a5","from_model"=>"Class_data","from_field"=>""],
["model"=>"Data_list3","field"=>"a4","from_model"=>"Class_data","from_field"=>""],
["model"=>"Data_list3","field"=>"a5","from_model"=>"Class_data","from_field"=>""],
["model"=>"News","field"=>"news_class_id","from_model"=>"News_class","from_field"=>""],
["model"=>"News","field"=>"news_class_mulit","from_model"=>"News_class","from_field"=>""],
["model"=>"News1","field"=>"news_class_id","from_model"=>"News_class1","from_field"=>""],
["model"=>"News1","field"=>"news_class_mulit","from_model"=>"News_class1","from_field"=>""],
["model"=>"News2","field"=>"news_class_id","from_model"=>"News_class2","from_field"=>""],
["model"=>"News2","field"=>"news_class_mulit","from_model"=>"News_class2","from_field"=>""],
["model"=>"News3","field"=>"news_class_id","from_model"=>"News_class3","from_field"=>""],
["model"=>"News3","field"=>"news_class_mulit","from_model"=>"News_class3","from_field"=>""],
			//AddModelUp
		];
		return $array;
	}
}